# -*- coding: utf-8 -*-
"""Researched source data for the NYC affordable-housing tracker.
All figures verified against the linked official advertisement / source on 2026-09-18.
"""
import datetime as dt

TODAY = dt.date(2026, 9, 18)

HC = "https://housingconnect.nyc.gov/PublicWeb/details/"
HDCROOT = "https://www.nychdc.com/sites/default/files/"

# ---------------------------------------------------------------- opportunities
# max1/max2/max3 : "N/A" = no unit for that household size, None = not published
def O(**k):
    d = dict(pub=None, deadline=None, max1=None, max2=None, max3=None,
             minimum=None, asset=None, mepref="UNCERTAIN", prefpct=None,
             laundry="", elevator="", amen="", status="NEW", notes="",
             appurl=None, side="n/a", cb="", walk=None, lines="", station="",
             route="", direct="NO", transfers=1, ttype="Easy same-station",
             tdetail="", dest="Freeman St", ride=None, utilinc="", util=0)
    d.update(k)
    return d

OPPS = [
    # ---------------------------------------------------------------- MANHATTAN
    O(id="MAN-001", name="The Lirio", addr="364 W 54th St, New York, NY 10019",
      hood="Hell's Kitchen / Clinton", boro="Manhattan", side="West", cb="Manhattan CB 4",
      corridor="Manhattan", url=HC+"7597", appurl=HC+"7597",
      program="HPD Supportive Housing Loan Program + Inclusionary Housing (new construction lottery)",
      deadline=dt.date(2026,10,5), unit="2 Bedroom", beds=2, ami="30% AMI",
      minimum=35315, max1="N/A", max2=40710, max3=45810, rent=863, asset=50880,
      utilinc="Water + gas heat included; tenant pays electricity", util=60,
      mepref="YES", prefpct=0.10,
      station="59 St-Columbus Circle (1/A/B/C/D)", lines="1 A B C D", walk=9,
      route="Walk to 59 St-Columbus Circle -> 1 uptown -> cross-platform to 2 at 96 St -> 2 to Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="96 St: the 1, 2 and 3 share island platforms - cross-platform, step-free",
      dest="Freeman St", ride=31, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, gym, sun terrace, library, party rooms, bike storage",
      notes="Lottery advertises NO studio/1BR. Minimum household size is 2, so a 1-person household cannot apply to any unit here. Also carries 20% Manhattan CB4 preference and 10% Municipal Employee/Military Veteran preference."),
    O(id="MAN-002", name="The Lirio", addr="364 W 54th St, New York, NY 10019",
      hood="Hell's Kitchen / Clinton", boro="Manhattan", side="West", cb="Manhattan CB 4",
      corridor="Manhattan", url=HC+"7597", appurl=HC+"7597",
      program="HPD Supportive Housing Loan Program + Inclusionary Housing (new construction lottery)",
      deadline=dt.date(2026,10,5), unit="2 Bedroom", beds=2, ami="77% AMI",
      minimum=100766, max1="N/A", max2=104489, max3=117579, rent=2772, asset=130592,
      utilinc="Water + gas heat included; tenant pays electricity", util=60,
      mepref="YES", prefpct=0.10,
      station="59 St-Columbus Circle (1/A/B/C/D)", lines="1 A B C D", walk=9,
      route="Walk to 59 St-Columbus Circle -> 1 uptown -> cross-platform to 2 at 96 St -> 2 to Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="96 St: the 1, 2 and 3 share island platforms - cross-platform, step-free",
      dest="Freeman St", ride=31, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, gym, sun terrace, library, party rooms, bike storage",
      notes="Reachable ONLY as a 2- or 3-person household. A 2-person household needs combined income $100,766-$104,489 - a narrow band."),
    O(id="MAN-003", name="The Lirio", addr="364 W 54th St, New York, NY 10019",
      hood="Hell's Kitchen / Clinton", boro="Manhattan", side="West", cb="Manhattan CB 4",
      corridor="Manhattan", url=HC+"7597", appurl=HC+"7597",
      program="HPD Supportive Housing Loan Program + Inclusionary Housing (new construction lottery)",
      deadline=dt.date(2026,10,5), unit="2 Bedroom", beds=2, ami="100% AMI",
      minimum=117772, max1="N/A", max2=135700, max3=152700, rent=3268, asset=169600,
      utilinc="Water + gas heat included; tenant pays electricity", util=60,
      mepref="YES", prefpct=0.10,
      station="59 St-Columbus Circle (1/A/B/C/D)", lines="1 A B C D", walk=9,
      route="Walk to 59 St-Columbus Circle -> 1 uptown -> cross-platform to 2 at 96 St -> 2 to Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="96 St: the 1, 2 and 3 share island platforms - cross-platform, step-free",
      dest="Freeman St", ride=31, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, gym, sun terrace, library, party rooms, bike storage",
      notes="2-person household band $117,772-$135,700. Rent $3,268 is far above the affordability target for this income."),
    O(id="MAN-004", name="The Lirio", addr="364 W 54th St, New York, NY 10019",
      hood="Hell's Kitchen / Clinton", boro="Manhattan", side="West", cb="Manhattan CB 4",
      corridor="Manhattan", url=HC+"7597", appurl=HC+"7597",
      program="HPD Supportive Housing Loan Program + Inclusionary Housing (new construction lottery)",
      deadline=dt.date(2026,10,5), unit="3 Bedroom", beds=3, ami="80% AMI",
      minimum=116400, max1="N/A", max2="N/A", max3=122160, rent=3186, asset=135680,
      utilinc="Water + gas heat included; tenant pays electricity", util=60,
      mepref="YES", prefpct=0.10,
      station="59 St-Columbus Circle (1/A/B/C/D)", lines="1 A B C D", walk=9,
      route="Walk to 59 St-Columbus Circle -> 1 uptown -> cross-platform to 2 at 96 St -> 2 to Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="96 St: the 1, 2 and 3 share island platforms - cross-platform, step-free",
      dest="Freeman St", ride=31, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, gym, sun terrace, library, party rooms, bike storage",
      notes="3-person household only. Combined income band $116,400-$122,160."),

    O(id="MAN-010", name="The Carolina", addr="1465 Park Avenue, New York, NY 10029",
      hood="East Harlem", boro="Manhattan", side="East", cb="Manhattan CB 11",
      corridor="Manhattan",
      url=HDCROOT+"2026-08/The%20Carolina%20remarketing%208.2026%20%281%29.pdf",
      appurl="mailto:Carleasing@manhattannorth.com",
      program="HDC re-rental - immediate vacancies & replenish waiting list",
      deadline=None, unit="1 Bedroom", beds=1, ami="165% AMI",
      minimum=118823, max1=196020, max2=223905, max3=251995, rent=3357.67, asset=279840,
      utilinc="Heat, hot water and gas for cooking included", util=70,
      mepref="NO", prefpct=None,
      station="103 St (6)", lines="6 (also 2/3 at 110 St)", walk=5,
      route="Walk to 103 St (6) -> 6 to 125 St -> cross-platform to 5 -> 5 to Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="125 St: 4/5/6 share island platforms - true cross-platform transfer",
      dest="Freeman St", ride=20, laundry="Yes", elevator="Yes",
      amen="Bicycle storage, laundry rooms, fitness center, landscaped courtyard, roof terraces",
      notes="Excellent commute but the 165% AMI minimum of $118,823 is far above this income. Alternative route: walk 12 min to 110 St and take the 2 direct (18 min). Ad lists only a mobility preference - no ME/MV preference on this re-rental."),
    O(id="MAN-011", name="The Carolina", addr="1465 Park Avenue, New York, NY 10029",
      hood="East Harlem", boro="Manhattan", side="East", cb="Manhattan CB 11",
      corridor="Manhattan",
      url=HDCROOT+"2026-08/The%20Carolina%20remarketing%208.2026%20%281%29.pdf",
      appurl="mailto:Carleasing@manhattannorth.com",
      program="HDC re-rental - immediate vacancies & replenish waiting list",
      deadline=None, unit="2 Bedroom", beds=2, ami="165% AMI",
      minimum=145799, max1="N/A", max2=223905, max3=251995, rent=4110.47, asset=279840,
      utilinc="Heat, hot water and gas for cooking included", util=70,
      mepref="NO", prefpct=None,
      station="103 St (6)", lines="6 (also 2/3 at 110 St)", walk=5,
      route="Walk to 103 St (6) -> 6 to 125 St -> cross-platform to 5 -> 5 to Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="125 St: 4/5/6 share island platforms - true cross-platform transfer",
      dest="Freeman St", ride=20, laundry="Yes", elevator="Yes",
      amen="Bicycle storage, laundry rooms, fitness center, landscaped courtyard, roof terraces",
      notes="Even a 2-person household needs $145,799 minimum. Out of reach."),

    O(id="MAN-020", name="Sunrose Tower Apartments (Unit 17E)",
      addr="620 W 153rd Street, New York, NY 10031",
      hood="Hamilton Heights", boro="Manhattan", side="West", cb="Manhattan CB 9",
      corridor="Manhattan", url="https://iaffordny.com/re-rentals",
      appurl="https://iaffordny.com/re-rentals",
      program="Re-rental (rent-stabilized 421-a/485-x), marketed by iAfford NY",
      deadline=None, unit="1 Bedroom", beds=1, ami="130% AMI",
      minimum=98331, max1=154440, max2=176410, max3=198510, rent=2678, asset=220480,
      utilinc="Tenant responsible for electricity including electric stove and heat", util=150,
      mepref="NO", prefpct=None,
      station="157 St (1)", lines="1", walk=4,
      route="Walk to 157 St (1) -> 1 SOUTH to 96 St -> cross-platform to 2 -> 2 north to Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="96 St: cross-platform 1 -> 2. Note the trip back-tracks ~3 miles south before heading north",
      dest="Freeman St", ride=35, laundry="Yes", elevator="Yes",
      amen="Gym, business centre, roof terrace, bike storage, dog wash, dishwasher, garage",
      notes="West Side Manhattan and a 4-minute walk to the 1, but the 130% AMI minimum of $98,331 is well above this income. Electric heat makes the true housing cost materially higher than the rent."),

    O(id="MAN-030", name="88 Leonard St (Unit 1210)", addr="88 Leonard Street, New York, NY 10013",
      hood="Tribeca", boro="Manhattan", side="West", cb="Manhattan CB 1",
      corridor="Manhattan", url="https://www.mns.com/affordable_units",
      appurl="https://www.mns.com/affordable_units",
      program="Affordable re-rental marketed by MNS", deadline=None,
      unit="Studio", beds=0, ami="Not published", minimum=None, max1=None, max2=None, max3=None,
      rent=3344, asset=None, utilinc="Not published", util=85,
      mepref="UNCERTAIN", prefpct=None,
      station="Chambers St (1/2/3)", lines="1 2 3 A C E", walk=7,
      route="Walk to Chambers St -> 2 direct to Freeman St",
      direct="YES", transfers=0, ttype="None", tdetail="No transfer - direct 2 train",
      dest="Freeman St", ride=40, laundry="", elevator="Yes",
      amen="Outdoor space",
      notes="Direct 2 train, but MNS does not publish income bands - must request the advertisement. Rent is far above the absolute maximum regardless."),

    O(id="MAN-040", name="Riverwalk Park (mobility unit)", addr="460 Main Street, New York, NY 10044",
      hood="Roosevelt Island", boro="Manhattan", side="n/a", cb="Manhattan CB 8",
      corridor="Not on Manhattan island",
      url=HDCROOT+"2026-07/Riverwalk%20Park%20Mobility%20Unit%20Remarketing%207.2026%20%281%29.pdf",
      appurl=None, program="HDC re-rental - mobility-adapted unit", deadline=None,
      unit="3 Bedroom", beds=3, ami="Not published", minimum=None, max1="N/A", max2="N/A", max3=None,
      rent=None, asset=None, utilinc="", util=0, mepref="NO",
      station="Roosevelt Island (F)", lines="F", walk=6,
      route="F to 63 St-Lexington Av -> walk to 59 St (4/5/6) -> 5 to Freeman St",
      direct="NO", transfers=2, ttype="Walking transfer",
      tdetail="63 St/Lex to 59 St Lexington Av complex is a long signed passageway",
      dest="Freeman St", ride=33, laundry="Yes", elevator="Yes", amen="Attended lobby, fitness centre",
      notes="EXCLUDED BY GEOGRAPHY RULE: Roosevelt Island is in Manhattan borough but is NOT on the island of Manhattan. Also 3-bedroom and mobility-designated."),

    # -------------------------------------------------- BROOKLYN - DIRECT 2/5
    O(id="BKN-001", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="Studio", beds=0, ami="30% AMI",
      minimum=18412, max1=35640, max2=40710, max3="N/A", rent=537, asset=50880,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="Rent $537 but the 30% AMI cap of $35,640 is far below this income."),
    O(id="BKN-002", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="Studio", beds=0, ami="40% AMI",
      minimum=25235, max1=47520, max2=54280, max3="N/A", rent=736, asset=67840,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="40% AMI cap $47,520 - below this income."),
    O(id="BKN-003", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="Studio", beds=0, ami="60% AMI",
      minimum=38880, max1=71280, max2=81420, max3="N/A", rent=1134, asset=101760,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="*** NEAR MISS *** $1,134 studio with utilities included. 1-person cap is $71,280 - this income is over by only $720. A 2-person household cap is $81,420, which WOULD fit. Watch this one if income or household size changes."),
    O(id="BKN-004", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="1 Bedroom", beds=1, ami="60% AMI",
      minimum=41658, max1=71280, max2=81420, max3=91620, rent=1215, asset=101760,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="*** NEAR MISS *** $1,215 one-bedroom, utilities included. Over the 1-person cap by $720. A 2- or 3-person household would clear it easily ($81,420 / $91,620)."),
    O(id="BKN-005", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="Studio", beds=0, ami="100% AMI",
      minimum=54583, max1=118800, max2=135700, max3="N/A", rent=1592, asset=169600,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="STRONGEST CURRENT MATCH. Eligible now, rent well under target, utilities included, and a workable one-transfer commute. Direct alternative: walk 10 min to Borough Hall and ride the 5 with no transfer (46 min)."),
    O(id="BKN-006", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="1 Bedroom", beds=1, ami="100% AMI",
      minimum=58492, max1=118800, max2=135700, max3=152700, rent=1706, asset=169600,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="Eligible now. A true one-bedroom under the rent target with utilities included - the best 1BR currently on the board."),
    O(id="BKN-007", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="Studio", beds=0, ami="120% AMI",
      minimum=68229, max1=142560, max2=162840, max3="N/A", rent=1990, asset=203520,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="Eligible but only just above the minimum ($68,229) - a fallback rather than a target."),
    O(id="BKN-008", name="90 Sands Apartments", addr="90 Sands Street, Brooklyn, NY 11201",
      hood="DUMBO", boro="Brooklyn", cb="Brooklyn CB 2", corridor="Brooklyn 2/5",
      url=HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf",
      appurl="mailto:intake@breakingground.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Breaking Ground)",
      deadline=None, unit="1 Bedroom", beds=1, ami="120% AMI",
      minimum=73098, max1=142560, max2=162840, max3=183240, rent=2132, asset=203520,
      utilinc="Owner responsible for electricity and gas; heat included in rent", util=0,
      mepref="NO", station="High St (A/C)", lines="A C (2/3/4/5 at Borough Hall)", walk=4,
      route="Walk to High St -> A/C to Fulton St (3 min) -> transfer in Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C and 4/5 connect inside one fare-controlled complex; signed, moderate walk",
      dest="Freeman St", ride=41, laundry="Yes", elevator="Yes",
      amen="24-hr attended lobby, on-site resident manager, fitness centre, computer room, multipurpose room",
      notes="*** NEAR MISS THE OTHER WAY *** minimum income is $73,098 - this income falls $1,098 SHORT. A small raise or a second earner flips this to eligible."),

    O(id="BKN-020", name="289 Fenimore Street (Unit 2B)", addr="289 Fenimore Street, Brooklyn, NY 11225",
      hood="Prospect Lefferts Gardens", boro="Brooklyn", cb="Brooklyn CB 9", corridor="Brooklyn 2/5",
      url="https://iaffordny.com/re-rentals", appurl="https://iaffordny.com/re-rentals",
      program="Re-rental marketed by iAfford NY", deadline=None,
      unit="1 Bedroom", beds=1, ami="Not published in listing index",
      minimum=None, max1=None, max2=None, max3=None, rent=2499.54, asset=None,
      utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="Winthrop St (2/5)", lines="2 5", walk=5,
      route="Walk to Winthrop St -> 2 or 5 direct to Freeman St (no transfer)",
      direct="YES", transfers=0, ttype="None", tdetail="No transfer - direct 2/5 service",
      dest="Freeman St", ride=64, laundry="", elevator="",
      amen="", notes="Direct 2/5 with a 5-minute walk, but the ride is over an hour and the rent is above the absolute maximum. Income bands not published in the index - open the listing to confirm."),
    O(id="BKN-021", name="80 Linden Boulevard (Unit 4E)", addr="80 Linden Boulevard, Brooklyn, NY 11226",
      hood="Prospect Lefferts Gardens / Flatbush", boro="Brooklyn", cb="Brooklyn CB 14",
      corridor="Brooklyn 2/5",
      url="https://iaffordny.com/re-rentals", appurl="https://iaffordny.com/re-rentals",
      program="Re-rental marketed by iAfford NY", deadline=None,
      unit="1 Bedroom", beds=1, ami="Not published in listing index",
      minimum=None, max1=None, max2=None, max3=None, rent=2700, asset=None,
      utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="Church Av (2/5)", lines="2 5", walk=8,
      route="Walk to Church Av -> 2 or 5 direct to Freeman St",
      direct="YES", transfers=0, ttype="None", tdetail="No transfer - direct 2/5 service",
      dest="Freeman St", ride=62, laundry="", elevator="",
      amen="", notes="Direct 2/5 but above the absolute rent maximum. Confirm income bands with the agent."),
    O(id="BKN-022", name="2510 Bedford Avenue (Unit 3E)", addr="2510 Bedford Avenue, Brooklyn, NY 11226",
      hood="Flatbush", boro="Brooklyn", cb="Brooklyn CB 14", corridor="Brooklyn 2/5",
      url="https://iaffordny.com/re-rentals", appurl="https://iaffordny.com/re-rentals",
      program="Re-rental marketed by iAfford NY", deadline=None,
      unit="1 Bedroom", beds=1, ami="Not published in listing index",
      minimum=None, max1=None, max2=None, max3=None, rent=2700, asset=None,
      utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="Beverly Rd (2/5)", lines="2 5", walk=7,
      route="Walk to Beverly Rd -> 2 or 5 direct to Freeman St",
      direct="YES", transfers=0, ttype="None", tdetail="No transfer - direct 2/5 service",
      dest="Freeman St", ride=66, laundry="", elevator="",
      amen="", notes="Direct 2/5 but above the absolute rent maximum. Confirm income bands with the agent."),

    # -------------------------------------------------- BROOKLYN - 3/4 (one easy transfer)
    O(id="BKN-030", name="Oceanhill I", addr="1743-1765 Prospect Place, Brooklyn, NY 11233",
      hood="Brownsville / Ocean Hill", boro="Brooklyn", cb="Brooklyn CB 16", corridor="Brooklyn 3/4",
      url=HDCROOT+"2026-06/OCEANHILL%201%20WAITLIST%205.2026.pdf",
      appurl="mailto:HOUSING@CORNELLPACE.COM",
      program="HDC re-rental - replenish waiting list (Cornell Pace)", deadline=None,
      unit="1-3 Bedroom", beds=1, ami="50% AMI",
      minimum=54515, max1=None, max2=None, max3=None, rent=1482, asset=84800,
      utilinc="Heat, hot water and cooking gas included; tenant pays electricity", util=75,
      mepref="NO", station="Saratoga Av (3)", lines="3 (4 at Utica Av)", walk=6,
      route="Walk to Saratoga Av -> 3 to Franklin Av (11 min) -> cross-platform to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="Franklin Av-Medgar Evers College: 2/3/4/5 share platforms - cross-platform transfer",
      dest="Freeman St", ride=65, laundry="Yes", elevator="",
      amen="Live-in superintendent, on-site laundry, security cameras, video intercom, parking (fee)",
      notes="Ad publishes a single combined band for 1-7 people ($54,515-$105,200), not per household size. The true 1-person cap at 50% AMI is $59,400, which this income exceeds. CALL CORNELL PACE to confirm the 1-person figure before discarding."),
    O(id="BKN-031", name="Oceanhill I", addr="1743-1765 Prospect Place, Brooklyn, NY 11233",
      hood="Brownsville / Ocean Hill", boro="Brooklyn", cb="Brooklyn CB 16", corridor="Brooklyn 3/4",
      url=HDCROOT+"2026-06/OCEANHILL%201%20WAITLIST%205.2026.pdf",
      appurl="mailto:HOUSING@CORNELLPACE.COM",
      program="HDC re-rental - replenish waiting list (Cornell Pace)", deadline=None,
      unit="1-3 Bedroom", beds=1, ami="60% AMI",
      minimum=65418, max1=None, max2=None, max3=None, rent=1800, asset=101760,
      utilinc="Heat, hot water and cooking gas included; tenant pays electricity", util=75,
      mepref="NO", station="Saratoga Av (3)", lines="3 (4 at Utica Av)", walk=6,
      route="Walk to Saratoga Av -> 3 to Franklin Av (11 min) -> cross-platform to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="Franklin Av-Medgar Evers College: 2/3/4/5 share platforms - cross-platform transfer",
      dest="Freeman St", ride=65, laundry="Yes", elevator="",
      amen="Live-in superintendent, on-site laundry, security cameras, video intercom, parking (fee)",
      notes="Rent $1,800 hits the target exactly. Published band is 1-7 people; the derived 1-person cap at 60% AMI is $71,280, so this income is likely over by $720 - but the ad does not say so explicitly. WORTH A PHONE CALL."),
    O(id="BKN-032", name="Oceanhill II", addr="1740-1760 Prospect Place & 396 Saratoga Avenue, Brooklyn, NY 11233",
      hood="Brownsville / Ocean Hill", boro="Brooklyn", cb="Brooklyn CB 16", corridor="Brooklyn 3/4",
      url=HDCROOT+"2026-06/OCEANHILL%202%20WAITLIST%205.2026.pdf",
      appurl="mailto:HOUSING@CORNELLPACE.COM",
      program="HDC re-rental - replenish waiting list (Cornell Pace)", deadline=None,
      unit="1-3 Bedroom", beds=1, ami="50% AMI",
      minimum=54515, max1=None, max2=None, max3=None, rent=1482, asset=84800,
      utilinc="Heat, hot water and cooking gas included; tenant pays electricity", util=75,
      mepref="NO", station="Saratoga Av (3)", lines="3 (4 at Utica Av)", walk=6,
      route="Walk to Saratoga Av -> 3 to Franklin Av (11 min) -> cross-platform to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="Franklin Av-Medgar Evers College: 2/3/4/5 share platforms - cross-platform transfer",
      dest="Freeman St", ride=65, laundry="Yes", elevator="",
      amen="Live-in super, coin laundry, outdoor recreation area, community room, parking (fee)",
      notes="Same combined-band issue as Oceanhill I. Confirm the 1-person cap with Cornell Pace."),
    O(id="BKN-033", name="Oceanhill II", addr="1740-1760 Prospect Place & 396 Saratoga Avenue, Brooklyn, NY 11233",
      hood="Brownsville / Ocean Hill", boro="Brooklyn", cb="Brooklyn CB 16", corridor="Brooklyn 3/4",
      url=HDCROOT+"2026-06/OCEANHILL%202%20WAITLIST%205.2026.pdf",
      appurl="mailto:HOUSING@CORNELLPACE.COM",
      program="HDC re-rental - replenish waiting list (Cornell Pace)", deadline=None,
      unit="1-3 Bedroom", beds=1, ami="60% AMI",
      minimum=65418, max1=None, max2=None, max3=None, rent=1800, asset=101760,
      utilinc="Heat, hot water and cooking gas included; tenant pays electricity", util=75,
      mepref="NO", station="Saratoga Av (3)", lines="3 (4 at Utica Av)", walk=6,
      route="Walk to Saratoga Av -> 3 to Franklin Av (11 min) -> cross-platform to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Same-platform",
      tdetail="Franklin Av-Medgar Evers College: 2/3/4/5 share platforms - cross-platform transfer",
      dest="Freeman St", ride=65, laundry="Yes", elevator="",
      amen="Live-in super, coin laundry, outdoor recreation area, community room, parking (fee)",
      notes="Rent $1,800 is on target. Confirm the 1-person cap with Cornell Pace before discarding."),

    # -------------------------------------------------- BROOKLYN - OTHER LINES
    O(id="BKN-040", name="Atlantic Chestnut Phase I", addr="250 Euclid Avenue, Brooklyn, NY 11208",
      hood="East New York", boro="Brooklyn", cb="Brooklyn CB 5", corridor="Brooklyn other",
      url=HDCROOT+"2026-09/Atlantic%20Chestnut%20Remarketing%209.2026.pdf",
      appurl="mailto:Rentals@phippsny.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Phipps)",
      deadline=None, unit="Studio", beds=0, ami="80% AMI",
      minimum=54206, max1=95040, max2=108560, max3="N/A", rent=1485, asset=135680,
      utilinc="Heat, hot water and gas for cooking included; tenant pays electricity", util=75,
      mepref="NO", station="Euclid Av (A/C)", lines="A C J", walk=6,
      route="Walk to Euclid Av -> A express to Fulton St (24 min) -> Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C to 4/5 inside one complex - easy but the total ride is very long",
      dest="Freeman St", ride=62, laundry="Yes", elevator="Yes",
      amen="Landscaped courtyard, roof deck with gardening beds, playroom, party room, gym, bike storage, 24/7 staffed entry",
      notes="*** EXCEPTIONAL VALUE, POOR COMMUTE *** Eligible now at $1,485 (24.8% of gross). But East New York is off the 2/5 corridor and door-to-door is roughly 80 minutes each way. Flagged deliberately rather than hidden - the rent is the best of any eligible unit found."),
    O(id="BKN-041", name="Atlantic Chestnut Phase I", addr="250 Euclid Avenue, Brooklyn, NY 11208",
      hood="East New York", boro="Brooklyn", cb="Brooklyn CB 5", corridor="Brooklyn other",
      url=HDCROOT+"2026-09/Atlantic%20Chestnut%20Remarketing%209.2026.pdf",
      appurl="mailto:Rentals@phippsny.org",
      program="HDC re-rental - immediate vacancies & replenish waiting list (Phipps)",
      deadline=None, unit="1 Bedroom", beds=1, ami="80% AMI",
      minimum=55132, max1=95040, max2=108560, max3=122160, rent=1500, asset=135680,
      utilinc="Heat, hot water and gas for cooking included; tenant pays electricity", util=75,
      mepref="NO", station="Euclid Av (A/C)", lines="A C J", walk=6,
      route="Walk to Euclid Av -> A express to Fulton St (24 min) -> Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center: A/C to 4/5 inside one complex - easy but the total ride is very long",
      dest="Freeman St", ride=62, laundry="Yes", elevator="Yes",
      amen="Landscaped courtyard, roof deck with gardening beds, playroom, party room, gym, bike storage, 24/7 staffed entry",
      notes="*** EXCEPTIONAL VALUE, POOR COMMUTE *** A one-bedroom for $1,500 (25.0% of gross) and eligible today. Same ~80 minute commute caveat as the studio."),
    O(id="BKN-050", name="962 Bushwick Avenue (Unit 3C)", addr="962 Bushwick Avenue, Brooklyn, NY 11221",
      hood="Bushwick", boro="Brooklyn", cb="Brooklyn CB 4", corridor="Brooklyn other",
      url="https://www.taxaceny.com/projects-8", appurl="https://www.taxaceny.com/projects-8",
      program="Re-rental marketed by Taxace NY", deadline=None,
      unit="Studio", beds=0, ami="Not stated", minimum=104812, max1=168480, max2=None, max3=None,
      rent=2850, asset=None, utilinc="Tenant's responsibility", util=110, mepref="UNCERTAIN",
      station="Gates Av (J/Z) / Myrtle-Wyckoff (L/M)", lines="J Z L M", walk=7,
      route="J to Fulton St -> Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center complex", dest="Freeman St", ride=58, laundry="", elevator="Yes",
      amen="Elevator building",
      notes="Minimum income $104,812 - well above this income. Listed for completeness."),
    O(id="BKN-051", name="962 Bushwick Avenue (Units 2A/3B/4B)", addr="962 Bushwick Avenue, Brooklyn, NY 11221",
      hood="Bushwick", boro="Brooklyn", cb="Brooklyn CB 4", corridor="Brooklyn other",
      url="https://www.taxaceny.com/projects-8", appurl="https://www.taxaceny.com/projects-8",
      program="Re-rental marketed by Taxace NY", deadline=None,
      unit="1 Bedroom", beds=1, ami="Not stated", minimum=112218, max1=189540, max2=None, max3=None,
      rent=2999, asset=None, utilinc="Tenant's responsibility", util=110, mepref="UNCERTAIN",
      station="Gates Av (J/Z) / Myrtle-Wyckoff (L/M)", lines="J Z L M", walk=7,
      route="J to Fulton St -> Fulton Center to 5 -> Freeman St",
      direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="Fulton Center complex", dest="Freeman St", ride=58, laundry="", elevator="Yes",
      amen="Elevator building",
      notes="Three identical units available. Minimum income $112,218 - out of reach."),
    O(id="BKN-060", name="Greenpoint Central (65 Dupont St, Unit 202)", addr="65 Dupont Street, Brooklyn, NY 11222",
      hood="Greenpoint", boro="Brooklyn", cb="Brooklyn CB 1", corridor="Brooklyn other",
      url="https://www.mns.com/affordable_units", appurl="https://afny.org/re-rentals",
      program="Re-rental marketed by MNS / Affordable For NY", deadline=None,
      unit="Studio", beds=0, ami="Not published", minimum=None, max1=None, max2=None, max3=None,
      rent=3160, asset=None, utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="Greenpoint Av (G)", lines="G", walk=8,
      route="G to Hoyt-Schermerhorn -> A/C to Fulton St -> 5 to Freeman St",
      direct="NO", transfers=2, ttype="Walking transfer",
      tdetail="Two transfers; the G is the slowest link in the network for this trip",
      dest="Freeman St", ride=70, laundry="", elevator="Yes", amen="Outdoor space",
      notes="Far above the rent maximum and a two-transfer commute. Recorded so it is not re-reviewed each week."),
    O(id="BKN-061", name="Greenpoint Central (65 Dupont St, Unit 320)", addr="65 Dupont Street, Brooklyn, NY 11222",
      hood="Greenpoint", boro="Brooklyn", cb="Brooklyn CB 1", corridor="Brooklyn other",
      url="https://www.mns.com/affordable_units", appurl="https://afny.org/re-rentals",
      program="Re-rental marketed by MNS / Affordable For NY", deadline=None,
      unit="1 Bedroom", beds=1, ami="Not published", minimum=None, max1=None, max2=None, max3=None,
      rent=3661, asset=None, utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="Greenpoint Av (G)", lines="G", walk=8,
      route="G to Hoyt-Schermerhorn -> A/C to Fulton St -> 5 to Freeman St",
      direct="NO", transfers=2, ttype="Walking transfer",
      tdetail="Two transfers; the G is the slowest link in the network for this trip",
      dest="Freeman St", ride=70, laundry="", elevator="Yes", amen="Outdoor space",
      notes="Far above the rent maximum."),
    O(id="BKN-062", name="The Garrison", addr="Brooklyn, NY (address on listing)",
      hood="Brooklyn", boro="Brooklyn", cb="", corridor="Brooklyn other",
      url="https://iaffordny.com/re-rentals", appurl="https://iaffordny.com/re-rentals",
      program="Re-rental marketed by iAfford NY", deadline=None,
      unit="1 Bedroom", beds=1, ami="Not published", minimum=None, max1=None, max2=None, max3=None,
      rent=3500, asset=None, utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="See listing", lines="", walk=10,
      route="Confirm from listing", direct="NO", transfers=1, ttype="Easy same-station",
      tdetail="", dest="Freeman St", ride=60, laundry="", elevator="",
      amen="", notes="Above the rent maximum; address and bands need confirming from the listing."),
    O(id="BKN-063", name="649 Hart Street (Unit 2B)", addr="649 Hart Street, Brooklyn, NY 11221",
      hood="Bushwick", boro="Brooklyn", cb="Brooklyn CB 4", corridor="Brooklyn other",
      url="https://afny.org/re-rentals", appurl="https://afny.org/re-rentals",
      program="Re-rental marketed by Affordable For NY", deadline=None,
      unit="Studio", beds=0, ami="Not published", minimum=None, max1=None, max2=None, max3=None,
      rent=2950, asset=None, utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="Halsey St (L)", lines="L J M", walk=6,
      route="L to Broadway Junction -> A to Fulton St -> 5 to Freeman St",
      direct="NO", transfers=2, ttype="Walking transfer", tdetail="",
      dest="Freeman St", ride=66, laundry="", elevator="",
      amen="", notes="Above the rent maximum and two transfers."),
    O(id="BKN-064", name="75 Dupont Street (Unit 421)", addr="75 Dupont Street, Brooklyn, NY 11222",
      hood="Greenpoint", boro="Brooklyn", cb="Brooklyn CB 1", corridor="Brooklyn other",
      url="https://afny.org/re-rentals", appurl="https://afny.org/re-rentals",
      program="Re-rental marketed by Affordable For NY", deadline=None,
      unit="1 Bedroom", beds=1, ami="Not published", minimum=None, max1=None, max2=None, max3=None,
      rent=3661, asset=None, utilinc="Not published", util=85, mepref="UNCERTAIN",
      station="Greenpoint Av (G)", lines="G", walk=8,
      route="G to Hoyt-Schermerhorn -> A/C to Fulton St -> 5 to Freeman St",
      direct="NO", transfers=2, ttype="Walking transfer", tdetail="",
      dest="Freeman St", ride=70, laundry="", elevator="",
      amen="", notes="Above the rent maximum."),
    O(id="BKN-065", name="35 Commercial Street", addr="35 Commercial Street, Brooklyn, NY 11222",
      hood="Greenpoint", boro="Brooklyn", cb="Brooklyn CB 1", corridor="Brooklyn other",
      url=HDCROOT+"2026-05/H1H2%20-%20%20Replenish%20Waitlist%20-%205.2026.pdf",
      appurl=None, program="HDC re-rental - replenish waiting list", deadline=None,
      unit="2 Bedroom", beds=2, ami="110% AMI", minimum=None, max1="N/A", max2=None, max3=None,
      rent=None, asset=None, utilinc="", util=0, mepref="NO",
      station="Greenpoint Av (G)", lines="G", walk=10,
      route="G to Hoyt-Schermerhorn -> A/C to Fulton St -> 5 to Freeman St",
      direct="NO", transfers=2, ttype="Walking transfer", tdetail="",
      dest="Freeman St", ride=72, laundry="Yes", elevator="Yes",
      amen="Fitness centre, community room, courtyards, bike storage",
      notes="2-bedroom only at 110% AMI. No 1-person unit."),
]

# ------------------------------------------------------------------- transit
# ride times are MEDIAN SCHEDULED minutes, MTA GTFS weekday feed (valid 2026-05-26 to 2026-10-31),
# AM departures 06:30-08:30, measured to Freeman St and to 174 St.
TRANSIT = [
    # hood, station, lines, walkability, direct2, direct5, transfer, ttype, dest, freeman, st174, grade, notes
    ("Central Harlem", "135 St", "2 3", "Excellent - dense grid, Lenox Ave", "YES", "NO", "None", "None", "Freeman St", 14, 16,
     "A+", "THE best Manhattan station for this commute. 14 minutes to Freeman St, no transfer."),
    ("Central Harlem", "125 St", "2 3", "Excellent - major commercial corridor", "YES", "NO", "None", "None", "Freeman St", 16, 18,
     "A+", "Direct 2. Note: this is the LENOX AVE 125 St, not the 4/5/6 or A/B/C/D 125 St - they are separate stations with no free transfer."),
    ("Central Harlem", "116 St", "2 3", "Very good", "YES", "NO", "None", "None", "Freeman St", 17, 20,
     "A+", "Direct 2 from Lenox Ave."),
    ("Central Harlem", "110 St-Malcolm X Plaza", "2 3", "Very good", "YES", "NO", "None", "None", "Freeman St", 18, 20,
     "A+", "Direct 2. Southern end of the Lenox corridor; also walkable from East Harlem."),
    ("Upper West Side", "96 St", "1 2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 23, 26,
     "A+", "Direct 2 and the key 1<->2/3 cross-platform interchange. Best UWS option."),
    ("Upper West Side", "72 St", "1 2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 26, 28,
     "A", "Direct 2, cross-platform with the 1."),
    ("Midtown West / Times Sq", "Times Sq-42 St", "1 2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 30, 33,
     "A", "Direct 2 from the heart of Midtown."),
    ("Chelsea / Penn", "34 St-Penn Station", "1 2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 32, 34,
     "A", "Direct 2."),
    ("Chelsea / West Village", "14 St (7 Av)", "1 2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 35, 38,
     "A", "Direct 2. Free passageway to 14 St-8 Av (A/C/E/L)."),
    ("Tribeca", "Chambers St", "1 2 3", "Very good", "YES", "NO", "None", "None", "Freeman St", 40, 42,
     "A", "Direct 2."),
    ("Civic Center", "Park Place", "2 3", "Good", "YES", "NO", "None", "None", "Freeman St", 41, 44,
     "A", "Direct 2; connects to the WTC/Chambers St complex."),
    ("Financial District", "Fulton St", "2 3 4 5 A C J Z", "Very good", "YES", "YES", "None", "None", "Freeman St", 43, 38,
     "A", "Both a direct 2 (43 min) AND a direct 5 (38 min). The single best-connected station downtown."),
    ("Financial District", "Wall St (7 Av line)", "2 3", "Good", "YES", "NO", "None", "None", "Freeman St", 44, 47,
     "A", "Direct 2."),
    ("East Harlem", "125 St (Lexington)", "4 5 6", "Excellent", "NO", "YES", "None", "None", "Freeman St", 16, 18,
     "A+", "Direct 5, tied with 135 St as the fastest Manhattan option. 4/5/6 cross-platform here."),
    ("Upper East Side", "86 St", "4 5 6", "Excellent", "NO", "YES", "None", "None", "Freeman St", 21, 24,
     "A+", "Direct 5 from the UES."),
    ("Midtown East", "59 St", "4 5 6", "Excellent", "NO", "YES", "None", "None", "Freeman St", 25, 27,
     "A", "Direct 5."),
    ("Midtown East", "Grand Central-42 St", "4 5 6 7 S", "Excellent", "NO", "YES", "None", "None", "Freeman St", 27, 30,
     "A", "Direct 5."),
    ("Union Square / Gramercy", "14 St-Union Sq", "4 5 6 L N Q R W", "Excellent", "NO", "YES", "None", "None", "Freeman St", 32, 34,
     "A", "Direct 5; the most interconnected station on the East Side."),
    ("Civic Center", "Brooklyn Bridge-City Hall", "4 5 6", "Good", "NO", "YES", "None", "None", "Freeman St", 36, 38,
     "A", "Direct 5."),
    ("Financial District", "Bowling Green", "4 5", "Good", "NO", "YES", "None", "None", "Freeman St", 40, 43,
     "A", "Direct 5; southern terminal area for Manhattan 5 service."),
    ("Hamilton Heights / Washington Hts", "157 St / 145 St (1)", "1", "Very good", "NO", "NO", "YES", "Same-platform", "Freeman St", 35, 38,
     "C", "The 1 does NOT reach the Bronx 2/5 corridor. You must ride SOUTH to 96 St and cross-platform to the 2 - a ~3 mile back-track. Upper Manhattan west of Broadway is weaker than it looks."),
    ("Morningside Heights", "Cathedral Pkwy-110 St (1)", "1", "Very good", "NO", "NO", "YES", "Same-platform", "Freeman St", 33, 36,
     "C", "Same back-track problem: south to 96 St, then north on the 2."),
    ("Upper West Side (A/C)", "72 St / 81 St / 86 St (B/C)", "B C", "Excellent", "NO", "NO", "YES", "Walking transfer", "Freeman St", 40, 43,
     "C", "B/C to Columbus Circle or 59 St then walk/transfer to the 1, then 96 St to the 2. Two moves in practice."),
    ("Harlem (A/B/C/D)", "125 St (St Nicholas Av)", "A B C D", "Excellent", "NO", "NO", "YES", "Complicated", "Freeman St", 45, 48,
     "D", "TRAP: there is NO free transfer between 125 St (A/B/C/D) at St Nicholas Ave and 125 St (2/3) at Lenox Ave - they are half a mile apart. Requires a crosstown bus or a paid re-entry."),
    ("Washington Heights", "168 St", "1 A C", "Very good", "NO", "NO", "YES", "Walking transfer", "Freeman St", 42, 45,
     "D", "Long deep-level station, then a southbound back-track. Not recommended for this commute."),
    ("DUMBO / Brooklyn Heights", "High St (A/C)", "A C", "Excellent", "NO", "NO", "YES", "Easy same-station", "Freeman St", 41, 43,
     "B", "A/C 3 minutes to Fulton St, then 4/5 inside the Fulton Center complex. Fastest way out of DUMBO."),
    ("Brooklyn Heights", "Clark St", "2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 48, 50,
     "C", "Direct 2 with no transfer, but a long ride. Lift-only station."),
    ("Downtown Brooklyn", "Borough Hall", "2 3 4 5 R", "Excellent", "YES", "YES", "None", "None", "Freeman St", 46, 48,
     "C", "Direct 5 (46 min) or direct 2 (50 min). Best all-round Brooklyn station for this trip."),
    ("Boerum Hill", "Hoyt St", "2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 52, 54,
     "C", "Direct 2."),
    ("Boerum Hill", "Nevins St", "2 3 4 5", "Excellent", "YES", "YES", "None", "None", "Freeman St", 47, 50,
     "C", "Direct 5 (47 min). All four IRT services stop here."),
    ("Prospect Heights", "Atlantic Av-Barclays Ctr", "2 3 4 5 B D N Q R W", "Excellent", "YES", "YES", "None", "None", "Freeman St", 48, 51,
     "C", "Direct 5 (48 min), direct 2 (54 min). Huge interchange."),
    ("Park Slope", "Bergen St", "2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 56, 59,
     "C", "Direct 2 only - the 4/5 skip this station."),
    ("Park Slope", "Grand Army Plaza", "2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 58, 61,
     "C", "Direct 2 only."),
    ("Crown Heights", "Eastern Pkwy-Brooklyn Museum", "2 3", "Excellent", "YES", "NO", "None", "None", "Freeman St", 60, 62,
     "D", "Direct 2 only; an hour on the train."),
    ("Crown Heights", "Franklin Av-Medgar Evers College", "2 3 4 5", "Very good", "YES", "YES", "None", "None", "Freeman St", 54, 56,
     "C", "Direct 5 (54 min). This is also THE cross-platform point where the 3 and 4 meet the 2 and 5."),
    ("Crown Heights", "President St-Medgar Evers College", "2 5", "Very good", "YES", "YES", "None", "None", "Freeman St", 56, 59,
     "D", "Direct 2 and 5 on the Nostrand Ave line."),
    ("Crown Heights", "Sterling St", "2 5", "Good", "YES", "YES", "None", "None", "Freeman St", 66, 69,
     "D", "Direct but long."),
    ("Prospect Lefferts Gardens", "Winthrop St", "2 5", "Good", "YES", "YES", "None", "None", "Freeman St", 64, 70,
     "D", "Direct 2/5. Around an hour on the train."),
    ("Flatbush", "Church Av", "2 5", "Very good", "YES", "YES", "None", "None", "Freeman St", 62, 64,
     "D", "Direct 5 (62 min)."),
    ("Flatbush", "Beverly Rd", "2 5", "Good", "YES", "YES", "None", "None", "Freeman St", 66, 74,
     "D", "Direct but long."),
    ("Flatbush / Little Haiti", "Newkirk Av-Little Haiti", "2 5", "Good", "YES", "YES", "None", "None", "Freeman St", 73, 76,
     "D", "Direct but very long."),
    ("Midwood", "Flatbush Av-Brooklyn College", "2 5", "Very good", "YES", "YES", "None", "None", "Freeman St", 68, 71,
     "D", "Southern terminal. Direct 5 (68 min) - you always get a seat, but it is a 2.5 hour daily round trip."),
    ("Brownsville / Ocean Hill", "Saratoga Av", "3", "Fair", "NO", "NO", "YES", "Same-platform", "Freeman St", 65, 68,
     "D", "3 to Franklin Av (11 min), then cross-platform to the 5. Easy transfer, long trip."),
    ("East New York", "Euclid Av", "A C", "Fair", "NO", "NO", "YES", "Easy same-station", "Freeman St", 62, 64,
     "D", "A express to Fulton St (24 min), then 4/5 in the Fulton Center complex."),
]

# --------------------------------------------------------------------- rules
MH = "https://www.nyc.gov/assets/hpd/downloads/pdfs/services/marketing-handbook-8-21.pdf"
ADD = "https://www.nyc.gov/assets/hpd/downloads/pdfs/services/MH-addendum-MEMV-preference.pdf"
AMIURL = "https://www.nyc.gov/site/hpd/services-and-information/area-median-income.page"

RULES = [
 ("Income is GROSS, before any deductions",
  "Projected annual income is calculated by annualising current income documents. The handbook states: 'Gross income, before any expenses or deductions, is used to determine income eligibility, with the exception of self-employment income.'",
  "DECISIVE. Take-home pay, taxes, pre-tax commuter benefits, 403(b) and health premiums do NOT reduce countable income. A net figure of ~$60k is irrelevant; the marketing agent annualises the GROSS line on the DOE paystubs.",
  "HPD-HDC Marketing Handbook, Section 5-4.A(3)", MH, "2021-08 (current)", "2026-09-18"),
 ("Minimum income is checked as well as maximum",
  "Every advertised unit has a published minimum AND maximum income. Both must be met. Minimum income does not vary by household size; the maximum does.",
  "His real constraint is often the MINIMUM, not the maximum. At $72,000 he is below the minimum on most 120%+ AMI units.",
  "HPD-HDC Marketing Handbook, Section 5-4.B", MH, "2021-08 (current)", "2026-09-18"),
 ("The 60% AMI cliff",
  "For a 1-person household in 2026 the 60% AMI cap is $71,280 and the 70% cap is $83,160.",
  "CRITICAL. At $72,000 he is $720 over the 60% AMI ceiling. That single $720 locks him out of the cheapest units (e.g. the $1,134 studio at 90 Sands). His eligible band as a single applicant is roughly 70%-100% AMI.",
  "HPD Area Median Income page (2026 chart)", AMIURL, "2026", "2026-09-18"),
 ("Municipal Employee / Military Veteran preference - 10%",
  "Effective 15 November 2025, newly published lotteries include a 10% ME/MV preference, replacing the former 5% municipal employee preference. At least one household member must qualify.",
  "APPLIES TO HIM. A NYC DOE teacher is paid by the City of New York and therefore qualifies. In a multi-person household his status covers the whole household.",
  "Addendum to the HPD-HDC Marketing Handbook, Section 5-1(C)", ADD, "2025-11-15", "2026-09-18"),
 ("Municipal employee = 'paid by the City of New York'",
  "'A general list of New York City agencies is available at nyc.gov for reference, but to be eligible for this preference, the applicant must be paid by the City of New York.'",
  "DOE teachers are paid by the City. Keep DOE paystubs; they are the proof.",
  "Addendum, Section 5-1(C)(1)(a)", ADD, "2025-11-15", "2026-09-18"),
 ("Proof of municipal employment",
  "Documentation required is 'Paystubs issued by the City of New York'. The applicant must have been a City employee at the time of the application snapshot AND during processing.",
  "No special form. But he must still be employed by DOE when his log number comes up, which can be many months later.",
  "Addendum, Section 5-1(G) table", ADD, "2025-11-15", "2026-09-18"),
 ("Is there anything to tick in Housing Connect?",
  "The addendum only specifies a Housing Connect question for VETERAN status ('Have you ever served in the US Armed Forces, National Guard, or Reserves?'). It specifies no equivalent applicant-facing question for municipal employment - that is confirmed by the marketing agent from City paystubs during processing.",
  "Answer the veteran question honestly (NO). Do not assume a municipal-employee checkbox exists; make sure the Housing Connect profile lists the DOE as employer and keep paystubs ready.",
  "Addendum, Section 5-1(C) and 5-1(G)", ADD, "2025-11-15", "2026-09-18"),
 ("Preference does NOT appear on every lottery",
  "The preference applies to HPD- or HDC-financed projects. Verified in practice: The Lirio (HPD Supportive Housing + Inclusionary) advertises '10% Municipal Employee/Military Veteran'; 1718 Crotona Park East (485-x tax exemption) advertises no preference at all.",
  "Check the preference block on each individual advertisement rather than assuming. Record YES/NO/UNCERTAIN per listing.",
  "NYC Housing Connect listing pages", "https://housingconnect.nyc.gov/PublicWeb/details/7597", "2026-09-18", "2026-09-18"),
 ("NYC residents are processed BEFORE non-residents",
  "'When processing applicants for the municipal employee/military veteran preference, New York City residents must be processed before non-residents.' Separately, listings state 'Applicants who live in New York City receive a general preference for apartments.'",
  "MAJOR DISADVANTAGE while he lives in Westchester. It does not bar him from applying or winning, but he is processed after every NYC resident - including inside the municipal-employee preference pool.",
  "Addendum, Section 5-1(C)(2); Housing Connect listing text", ADD, "2025-11-15", "2026-09-18"),
 ("Community board preference - 20%",
  "A percentage of units is set aside for residents of the local community district. The Lirio advertises 20% for Manhattan CB4.",
  "He cannot use this from Westchester. It reduces the effective pool of units open to him by roughly a fifth on each lottery.",
  "NYC Housing Connect listing (The Lirio)", "https://housingconnect.nyc.gov/PublicWeb/details/7597", "2026-09-18", "2026-09-18"),
 ("Qualification as a household",
  "'Household' at admission means (i) a single person, or (ii) two or more persons who: a. are Immediate Family Members; b. are Extended Family Members who need to live together...; or c. are financially interdependent, as shown by a shared lease/utility record or shared bank accounts.",
  "KEY OPPORTUNITY. Applying with his brothers uses branch (a), the easiest branch. Combined income clears the minimum-income hurdles that block him alone, and raises the maximum caps.",
  "HPD-HDC Marketing Handbook, Section 5-2", MH, "2021-08 (current)", "2026-09-18"),
 ("SIBLINGS are Immediate Family Members",
  "'Immediate Family Member shall mean, with respect to any person, (i) his or her grandparent, parent, co-parent, or Guardian, child or Dependent, grandchild, SIBLING, spouse, or domestic partner...'",
  "DECISIVE FOR THE BROTHERS PLAN. Brothers qualify as one household automatically under branch (a). They do NOT have to prove financial interdependence - no shared lease, no shared bank account, no shared address needed beforehand. This is far easier than a household of friends.",
  "HPD-HDC Marketing Handbook, Section 5-2 (Definitions)", MH, "2021-08 (current)", "2026-09-18"),
 ("Multi-person household - what combines",
  "All household members' INCOME is combined and tested against the minimum and the household-size maximum. All members' ASSETS are combined against the single asset limit. No member may own residential property within 100 miles of NYC. Every member must surrender their current lease.",
  "With 2-3 brothers: incomes add (helps clear minimums, risks breaching maximums), assets add (one shared cap, not one each), and every brother must pass the property and primary-residence tests.",
  "HPD-HDC Marketing Handbook, Sections 5-4, 5-5", MH, "2021-08 (current)", "2026-09-18"),
 ("ASSET TEST 1 - the hard asset limit",
  "'For an affordable rental unit, the value of the applicant's household assets may not exceed the amount of the current HUD income limit for a four-person household for the AMI limit applicable to such unit.' A household of ANY size uses the four-person figure. The entire market value of real property counts; for other capital investments only the applicant's equity counts.",
  "Generous. 2026 four-person caps: 60% AMI $101,760; 80% $135,680; 100% $169,600; 120% $203,520. Combined brothers' savings are measured against ONE of these numbers, not one each.",
  "HPD-HDC Marketing Handbook, Section 5-5.A", MH, "2021-08 (current)", "2026-09-18"),
 ("What is EXCLUDED from the asset limit",
  "'Balances in specifically designated retirement funds, life insurance accounts, annuities, and college savings accounts are not subject to the asset limit.' Under HOTMA, 'necessary personal property' is excluded, and non-necessary personal property is only counted where the combined value exceeds the HUD-published threshold ($51,600 at handbook publication - use the current threshold at processing).",
  "His NYC TRS pension and any 403(b)/457 are invisible to the asset test. Ordinary savings, checking and brokerage balances are what count.",
  "HPD-HDC Marketing Handbook, Sections 5-5.A(4) and 5-4.I", MH, "2021-08 (current)", "2026-09-18"),
 ("ASSET TEST 2 - assets also ADD to income",
  "'Income generated from the asset(s) is added to employment and other income regardless of the total value of the household net assets.' Where total assets are at or above the HUD threshold, the agent computes actual income for each asset with determinable income and IMPUTED income for the rest, using the HUD passbook savings rate (0.45% as of January 2025), and adds the total to household income.",
  "SUBTLE BUT IMPORTANT. Savings do not just face a cap - the interest they earn is added to countable income and can push a household over an AMI maximum. At 0.45% the imputed amount is small (roughly $45 per $10,000), but real interest on a high-yield savings account is counted at its actual rate.",
  "HPD-HDC Marketing Handbook, Section 5-4.I(2)-(3)", MH, "2021-08 (current)", "2026-09-18"),
 ("Asset documentation thresholds",
  "All adult members must sign an asset certification. If total assets are below the HUD-published threshold, that self-certification is the ONLY documentation required. At or above the threshold, full third-party verification is required and documents must be current within 120 days of the tenant income certification date.",
  "Keeping combined liquid assets below the threshold materially reduces paperwork. Every adult brother signs.",
  "HPD-HDC Marketing Handbook, Section 5-4.I", MH, "2021-08 (current)", "2026-09-18"),
 ("Bank deposits get scrutinised",
  "Agents must review bank statements for unreported income. 'Consistent, recurring, determinable, and/or regular deposits' must be questioned and explained in writing - including transactions in apps such as Venmo and Cash App. Temporary, non-recurring and sporadic deposits are excluded.",
  "Regular transfers between brothers, tutoring income or side payments will be queried. Be ready to explain them in writing.",
  "HPD-HDC Marketing Handbook, Section 5-4.J", MH, "2021-08 (current)", "2026-09-18"),
 ("Sporadic and non-recurring income is excluded",
  "One-time gifts, lump-sum inheritances and holiday/birthday gifts are disclosed but excluded from the income calculation, being income that will not repeat in the next 12 months.",
  "A one-off family gift toward moving costs does not count as income - but it WILL count as an asset once it sits in the bank.",
  "HPD-HDC Marketing Handbook, Section 5-4.H", MH, "2021-08 (current)", "2026-09-18"),
 ("Sole primary residence - 270 days a year",
  "For a rental affordable unit the applicant must continuously occupy the unit as their sole primary residence, 'residing there no less than 270 calendar days per year'.",
  "Applies to every household member. A brother who actually lives elsewhere most of the year cannot be on the application.",
  "HPD-HDC Marketing Handbook, Section 5-5.C(3)", MH, "2021-08 (current)", "2026-09-18"),
 ("You must withdraw other applications once selected",
  "On being processed for a unit the applicant 'must also agree to withdraw any application(s) for other lotteries for which they are being processed'.",
  "Apply to everything, but expect to have to drop the rest once one comes through. Track this in the Application Tracker.",
  "HPD-HDC Marketing Handbook, Section 5-5.C(1)", MH, "2021-08 (current)", "2026-09-18"),
 ("Occupancy guidelines",
  "Studio 1-2 people; 1 Bedroom 1-3; 2 Bedroom 2-5; 3 Bedroom 3-7; 4 Bedroom 4-9. If a household qualifies for more than one unit size by both persons and income, 'the family chooses the unit size'.",
  "A 2-person household can take a studio or a 1BR; a 3-person household can still take a 1BR. This widens the search considerably.",
  "HPD-HDC Marketing Handbook, Section 5-7.A", MH, "2021-08 (current)", "2026-09-18"),
 ("Changing household composition mid-process = rejection",
  "After the application snapshot, changes to household composition that affect eligibility result in rejection unless caused by an Extenuating Circumstance (death, birth, separation/divorce, custody order, domestic violence).",
  "Decide the household BEFORE applying. Adding or dropping a roommate after applying will void the application.",
  "HPD-HDC Marketing Handbook, Section 5-3.B", MH, "2021-08 (current)", "2026-09-18"),
 ("Changing income mid-process",
  "A reported income change after eligibility is confirmed is only accepted if it is outside the applicant's control and documented by a third party; otherwise the application is rejected.",
  "A DOE step increase is documentable via the employer. But do not update the profile speculatively once a snapshot is taken.",
  "HPD-HDC Marketing Handbook, Section 5-3.A", MH, "2021-08 (current)", "2026-09-18"),
 ("The snapshot rule",
  "'Applicants are evaluated based on the information in their profile when their log number appears on a batch, at which time a snapshot of their profile is taken.' Once taken, information cannot be changed.",
  "Keep the Housing Connect profile continuously accurate - he never knows when the snapshot happens.",
  "HPD-HDC Marketing Handbook, Section 5-3", MH, "2021-08 (current)", "2026-09-18"),
 ("Asset limit for rentals",
  "'For an affordable rental unit, the value of the applicant's household assets may not exceed the amount of the current HUD income limit for a four-person household for the AMI limit applicable to such unit.' Retirement funds, life insurance, annuities and college savings are excluded.",
  "Generous at his level: e.g. $169,600 for a 100% AMI unit, $101,760 at 60% AMI. His NYC TRS pension and any 403(b) do NOT count. All members' assets count in a multi-person household.",
  "HPD-HDC Marketing Handbook, Section 5-5.A", MH, "2021-08 (current)", "2026-09-18"),
 ("No residential property within 100 miles",
  "'For a rental affordable unit, no member of the applicant's household may own any residential real property in, or within a 100-mile radius of, New York City.'",
  "Applies to every member of the household. Westchester property would disqualify.",
  "HPD-HDC Marketing Handbook, Section 5-5.B(3)", MH, "2021-08 (current)", "2026-09-18"),
 ("Primary residence / surrender current lease",
  "An approved applicant must surrender any unit where they currently reside, and each household member who leases must terminate that lease on or before move-in.",
  "The Westchester lease must end. Plan the overlap.",
  "HPD-HDC Marketing Handbook, Section 5-5.C", MH, "2021-08 (current)", "2026-09-18"),
 ("Mitchell-Lama is now on Housing Connect",
  "'Mitchell-Lama Connect has been decommissioned. All Mitchell-Lama lotteries are now conducted on Housing Connect.'",
  "Do not waste time on the old ML portal. Watching Housing Connect now also covers City-supervised Mitchell-Lama. State-supervised ML is separate (HCR).",
  "HPD Mitchell-Lama page", "https://www.nyc.gov/site/hpd/services-and-information/mitchell-lama-program.page", "2026", "2026-09-18"),
 ("Re-rentals happen outside Housing Connect",
  "HPD: 'Some affordable re-rentals and resales become available outside Housing Connect.' HPD publishes a list of ~39 marketing agents and property managers who advertise them directly.",
  "This is where most of his currently-actionable inventory is. Housing Connect alone would have shown him ZERO eligible units today.",
  "HPD Find Affordable Housing Re-Rentals",
  "https://www.nyc.gov/site/hpd/services-and-information/find-affordable-housing-re-rentals.page", "2026", "2026-09-18"),
 ("Credit check and fees",
  "Applicants may consent to a credit check (fee up to $20) or provide evidence of 12 months of full rent payment. Lotteries advertise no application fee and no broker fee.",
  "Budget a small credit-check fee. Keep 12 months of rent receipts as an alternative.",
  "Marketing agent standard FAQ (iAfford NY, HPD terms)", "https://iaffordny.com/re-rentals", "2026", "2026-09-18"),
]

# ----------------------------------------------------------------- documents
DOCS = [
 ("Photo ID (driver licence / state ID / passport)", "No", "Yes", "Must be current / unexpired", "", "", "", "Also used to evidence residency for preference purposes."),
 ("Social Security card or ITIN letter", "No", "Yes", "n/a", "", "", "", "For every household member."),
 ("DOE paystubs", "No", "Yes", "Most recent month (HPD reduced this from prior requirements)", "", "", "",
  "THE core document. Also the proof of municipal-employee status - the addendum requires 'Paystubs issued by the City of New York'. Keep a rolling PDF of the last 2 months from the DOE payroll portal."),
 ("Employment verification letter from DOE / HR", "No", "Yes", "Dated within ~60 days when requested", "", "", "",
  "Marketing agents send an Employer Verification form directly to the employer. Know your DOE HR contact."),
 ("Proof of current address", "No", "Yes", "Recent (utility bill, lease, bank statement)", "", "", "",
  "Westchester address. Needed even though it costs him the NYC residency preference."),
 ("Current lease", "No", "Yes", "Current term", "", "", "", "Also evidences the primary-residence rule and the surrender obligation."),
 ("Federal tax return / W-2", "No", "Sometimes", "Most recent tax year", "", "", "",
  "HPD reduced this for straightforward employed applicants, but agents still request it where income is unclear or where there is second income. Keep last 2 years."),
 ("Bank statements", "No", "Sometimes", "Most recent 2-6 months", "", "", "",
  "Generally not required where assets are under $50,000, but agents may still ask. Be ready to explain any recurring deposits (see handbook Example 3 on Venmo deposits)."),
 ("Asset documentation (brokerage, savings)", "No", "Yes if assets exist", "Most recent statement", "", "", "",
  "Retirement accounts (NYC TRS, 403(b)), life insurance, annuities and college savings are EXCLUDED from the asset limit - but list them so the agent can classify them."),
 ("Documentation of additional DOE income (per-session, coverage, summer)", "No", "Yes if applicable", "Current", "", "", "",
  "Per-session pay counts as income. Include it in the salary input or it will surface later and change eligibility."),
 ("Housing Connect profile - complete and current", "YES", "Yes", "Continuously", "", "", "",
  "The profile is snapshotted without warning when a log number comes up. Keep income, household and employer accurate at all times."),
 ("Evidence of financial interdependence (multi-person household only)", "No", "Yes", "Current", "", "", "",
  "Only if applying as a 2-3 person household: a shared lease or utility record at a shared address, or bank records showing shared assets/expenses. Build this BEFORE applying - it cannot be added later."),
 ("DD-214 or Statement of Service", "No", "Only if veteran", "n/a", "", "", "",
  "Not applicable here unless a household member has served."),
 ("Proof of no property ownership", "No", "If asked", "Current", "", "", "",
  "Self-certification usually; applies to all household members within 100 miles of NYC."),
]

# ------------------------------------------------------------------ sources
HPDRR = "https://www.nyc.gov/site/hpd/services-and-information/find-affordable-housing-re-rentals.page"
SOURCES = [
 ("NYC Housing Connect - open rental lotteries", "https://housingconnect.nyc.gov/PublicWeb/search-lotteries",
  "New-construction lotteries + Mitchell-Lama (all boroughs)", "New listings appear continuously; deadlines run 4-8 weeks",
  "Every 2-3 days", "2026-09-18", "PRIMARY SOURCE. 12 open rental lotteries citywide today, only 1 in Manhattan. Filter by borough, then open each listing - the summary does not show income bands."),
 ("NYC HDC re-rentals", "https://www.nychdc.com/find-re-rentals",
  "Re-rentals and replenish-waiting-lists in HDC-financed buildings", "Changes weekly; ads are dated PDFs",
  "Weekly", "2026-09-18", "HIGH YIELD. 24 listings today including 90 Sands and Atlantic Chestnut. Each has a downloadable advertisement PDF with full income tables."),
 ("HPD list of re-rental marketing agents", HPDRR,
  "The master directory of ~39 agents who advertise re-rentals outside Housing Connect", "Directory itself changes rarely; the agents' own pages change constantly",
  "Monthly (to catch new agents)", "2026-09-18", "THE most important discovery tool. Everything below came from this page."),
 ("HPD Affordable Rental and Homeownership Opportunities", "https://www.nyc.gov/site/hpd/services-and-information/housing-connect-rentals.page",
  "HPD overview and current opportunity announcements", "Occasional", "Monthly", "2026-09-18", ""),
 ("HPD Area Median Income chart", AMIURL, "Official AMI and income limits", "Annually (usually spring)", "Quarterly", "2026-09-18",
  "Re-check every spring - when the AMI chart updates, every income band in this workbook shifts."),
 ("NY State HCR - Mitchell-Lama automated waiting lists", "https://awl.hcr.ny.gov/waitinglist/appl_search.asp?pm=a",
  "State-supervised Mitchell-Lama open waiting lists", "Lists open and close unpredictably", "Monthly", "2026-09-18",
  "Separate from City-supervised ML. Login access is migrating to housingsearch.hcr.ny.gov."),
 ("NYS Housing Search", "https://housingsearch.hcr.ny.gov/", "State affordable housing search", "Continuous", "Monthly", "2026-09-18", ""),
 ("Affordable For NY", "https://afny.org/re-rentals", "Re-rentals (multiple boroughs)", "Weekly", "Weekly", "2026-09-18", "3 listings today - Brooklyn and Queens."),
 ("iAfford NY", "https://iaffordny.com/re-rentals", "Re-rentals", "Weekly", "Weekly", "2026-09-18", "8 listings today including Sunrose Tower (Manhattan) and several Brooklyn 2/5 addresses."),
 ("Infinite Horizons (ihrerentals)", "https://ihrerentals.com/", "HPD/HDC re-rentals and re-sales, immediate occupancy", "Weekly", "Weekly", "2026-09-18", "Listings live behind the photo gallery; contact rentals@ihrerentals.com."),
 ("Taxace NY", "https://www.taxaceny.com/projects-8", "Vacant available units", "Weekly", "Weekly", "2026-09-18", "Large list but predominantly Bronx; also the marketing agent for some Housing Connect lotteries."),
 ("MNS Real Estate", "https://www.mns.com/affordable_units", "Affordable units", "Weekly", "Weekly", "2026-09-18", "4 listings today including 88 Leonard St (Manhattan). Income bands not published - request the ad."),
 ("TF Cornerstone re-rentals", "https://tfc.com/about/affordable-re-rentals", "Re-rentals in TFC buildings (Manhattan, Brooklyn, LIC)", "Continuous", "Every 2 weeks", "2026-09-18",
  "Publishes full income tables. Currently LIC-heavy; bands run 40%-165% AMI."),
 ("Related - Affordable Housing Group", "https://ahgleasing.com/", "Related's affordable waiting lists", "Occasional", "Monthly", "2026-09-18",
  "No general waiting lists open today; only an accessibility-unit opportunity at 553 W 30th St."),
 ("Clinton Management", "https://www.clintonmanagement.com/availabilities/affordable/", "Affordable vacancies", "Occasional", "Monthly", "2026-09-18", "No vacancies today."),
 ("Wavecrest Rentals", "https://wavecrestrentals.com/section.php?id=1", "Ongoing waiting list applications", "Occasional", "Monthly", "2026-09-18",
  "Not accepting applications today. Their indicative 1-person cap of $68,040 is below this income."),
 ("Settlement Housing Fund", "https://www.settlementhousingfund.org/find-housing/", "Lotteries and re-rentals", "Occasional", "Monthly", "2026-09-18", ""),
 ("MGNY Consulting", "https://mgnyconsulting.com/listings/", "Re-rentals", "Weekly", "Every 2 weeks", "", ""),
 ("CGMR Compliance", "https://cgmrcompliance.com/housing-opportunities", "Re-rentals", "Unknown", "Monthly", "2026-09-18", "Returned 404 today - re-check or remove."),
 ("City5", "https://city5.nyc/", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("Fifth Avenue Committee", "https://fifthave.org/re-rental-availabilities/", "Brooklyn re-rentals", "Occasional", "Monthly", "", "Brooklyn-focused - relevant to the 2/5 corridor."),
 ("Housing Partnership", "https://housingpartnership.com/what-we-do/current-vacancies/", "Current vacancies", "Occasional", "Monthly", "2026-09-18", "Page carried no listings today."),
 ("Ibis Advisors", "https://ibis.powerappsportals.com/", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("K&G Upright", "https://kgupright.com/", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("Langsam Property Services", "https://www.langsampropertyservices.com/affordable-rental-opportunities", "Re-rentals", "Occasional", "Monthly", "", ""),
 ("MHANY / Mutual Housing NY", "https://www.mutualhousingny.org/affordable-re-rental-units", "Re-rentals", "Occasional", "Monthly", "", ""),
 ("Micki Garcia Realty", "https://www.mickigarciarealty.com/", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("Pronto Housing", "https://www.prontohousingrentals.com/", "Re-rentals", "Weekly", "Every 2 weeks", "", ""),
 ("Reclaim HDFC", "https://sbmgmt.sitemanager.rentmanager.com/RECLAIMHDFC.aspx", "HDFC re-rentals", "Unknown", "Monthly", "", ""),
 ("Reside New York", "https://residenewyork.com/property-status/open-market/", "Open-market and affordable", "Weekly", "Monthly", "", ""),
 ("RiseBoro", "https://riseboro.org/housing/woodlawn-senior-living/", "Mostly senior housing", "Occasional", "Quarterly", "", "Age-restricted - low relevance."),
 ("Riverton Square", "https://streeteasy.com/building/riverton-square", "Harlem rental complex", "Continuous", "Monthly", "", "Harlem, near the 2/3 at 135 St - worth watching for the commute alone."),
 ("SJP Tax Consultants", "https://www.sjpny.com/affordable-rerentals", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("SOIS Real Estate Consulting", "https://soisrealestateconsulting.com/current-projects-1", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("Spring Leasing and Management", "https://springmanagement.net/apartments-for-rent/", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("Stanton Norfolk (East Village Homes)", "https://east-village-homes-owner-llc.rentcafewebsite.com/", "Manhattan (East Village) re-rentals", "Occasional", "Monthly", "", "One of the few Manhattan-specific agents on HPD's list."),
 ("St Nicks Alliance", "https://stnicksalliance.org/get-help-affordable-housing/", "Brooklyn re-rentals", "Occasional", "Monthly", "", ""),
 ("Sterling23", "https://www.sterling23.com/?page=affordable", "Re-rentals", "Occasional", "Monthly", "2026-09-18", "Astoria-based; current listing is Bronx - excluded by geography."),
 ("Tax Solute / Affordable Living NYC", "https://sites.google.com/affordablelivingnyc.com/hpd/home", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("Your Neighborhood Housing", "https://yourneighborhoodhousing.com/", "Re-rentals", "Unknown", "Monthly", "", ""),
 ("StreetEasy", "https://streeteasy.com/", "Market + some affordable/stabilised listings", "Continuous", "Weekly", "", "HPD explicitly points here. Search 'income restricted'."),
 ("AffordableHousing.com", "https://www.affordablehousing.com/", "National affordable listings", "Continuous", "Monthly", "", "HPD-listed."),
 ("HPD Mitchell-Lama program page", "https://www.nyc.gov/site/hpd/services-and-information/mitchell-lama-program.page",
  "City-supervised Mitchell-Lama", "Rarely", "Quarterly", "2026-09-18", "Confirms ML lotteries now run through Housing Connect."),
 ("MTA official subway schedules", "https://www.mta.info/schedules/subway/2-train", "Service patterns for the 2 and 5", "Service changes are frequent at weekends", "Before any final decision", "2026-09-18",
  "Use to sanity-check commute assumptions and weekend/late-night patterns before signing a lease."),
]

# ------------------------------------------------------------- inbox seeds
INBOX = [
 ("2026-09-18", "The Lirio", "364 W 54th St", "Hell's Kitchen", "NYC Housing Connect",
  HC+"7597", "2026-10-05", "No", "No", "No - min HH size 2", "n/a", "Yes - B grade", "Yes", "Yes",
  "Only open Manhattan lottery. No studio/1BR at all; 1-person household cannot apply. Viable only as a 2-3 person household."),
 ("2026-09-18", "90 Sands Apartments", "90 Sands St, DUMBO", "DUMBO", "NYC HDC re-rentals",
  HDCROOT+"2026-06/90%20Sands%20Remarketing%206.25.26.pdf", "Ongoing", "Yes", "Yes", "Yes - 100% & 120% AMI", "Yes", "Yes - B grade", "Yes", "Yes",
  "BEST CURRENT MATCH. Studio $1,592 / 1BR $1,706 at 100% AMI, utilities included."),
 ("2026-09-18", "Atlantic Chestnut Phase I", "250 Euclid Ave", "East New York", "NYC HDC re-rentals",
  HDCROOT+"2026-09/Atlantic%20Chestnut%20Remarketing%209.2026.pdf", "Ongoing", "Yes", "Yes", "Yes - 80% AMI", "Yes - excellent", "Weak - D grade", "Yes", "Yes",
  "Cheapest eligible units found ($1,485 / $1,500) but ~80 min commute and off the 2/5 corridor."),
 ("2026-09-18", "The Carolina", "1465 Park Ave", "East Harlem", "NYC HDC re-rentals",
  HDCROOT+"2026-08/The%20Carolina%20remarketing%208.2026%20%281%29.pdf", "Ongoing", "No", "Yes", "No - min $118,823", "No", "Yes - excellent", "Yes", "Yes",
  "Great location and commute; income minimum far too high."),
 ("2026-09-18", "Sunrose Tower", "620 W 153rd St", "Hamilton Heights", "iAfford NY",
  "https://iaffordny.com/re-rentals", "Ongoing", "No", "Yes", "No - min $98,331", "No", "Moderate - C grade", "Yes", "Yes",
  "West Side Manhattan 1BR but 130% AMI minimum is out of reach."),
 ("2026-09-18", "Oceanhill I & II", "Prospect Place, Brownsville", "Brownsville", "NYC HDC re-rentals",
  HDCROOT+"2026-06/OCEANHILL%201%20WAITLIST%205.2026.pdf", "Ongoing", "No", "Yes", "REVIEW - ad gives combined 1-7 person band", "Yes - $1,482-$1,800", "Weak - D grade", "Yes", "Yes",
  "ACTION: phone Cornell Pace (914-380-8220 x4018) to get the 1-person income cap."),
 ("2026-09-18", "289 Fenimore St", "289 Fenimore St", "Prospect Lefferts Gardens", "iAfford NY",
  "https://iaffordny.com/re-rentals", "Ongoing", "No", "Yes", "REVIEW - not published", "No - $2,499", "Yes - direct 2/5", "Yes", "Yes",
  "Direct 2/5 five minutes away but rent is above the absolute maximum."),
 ("2026-09-18", "88 Leonard St", "88 Leonard St", "Tribeca", "MNS",
  "https://www.mns.com/affordable_units", "Ongoing", "Yes", "No", "REVIEW - not published", "No - $3,344", "Yes - direct 2", "Yes", "Yes",
  "Manhattan studio, direct 2 train, but rent far above maximum."),
]
